vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        
    mappings:
        fichier:
            uri_prefix: /fichier/exercice
            upload_destination: '%kernel.project_dir%/public/fichier/exercice'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true